### ISSUE TITLE
Seed number not displaying same generated icons as jazzicon-js

### ISSUE THREAD

**Issue by Perronef5** [bigearsenal/JazziconSwift#1]
Hi I tried using this earlier today and it seems the incorrect images are being generated when given the same seed number. I am currently trying to see if I can find the solution to this.

**Comment by bigearsenal** [comment]
Thank you. I'm also thinking abt it

**Comment by Perronef5** [comment]
> Thank you. I'm also thinking abt it

Anywhere you think the bug is at?

**Comment by bigearsenal** [comment]
> > Thank you. I'm also thinking abt it
> 
> Anywhere you think the bug is at?

I think the rotation causes the bug, but I'm not quite sure

**Comment by Perronef5** [comment]
> > > Thank you. I'm also thinking abt it
> > 
> > 
> > Anywhere you think the bug is at?
> 
> I think the rotation causes the bug, but I'm not quite sure

Interesting. Will look into the rotation logic

**Comment by Perronef5** [comment]
I see `generator.nextUniform()` is generating a different number then its `js` counterpart `generator.random();`.

Maybe `MersenneTwister` and `GKMersenneTwisterRandomSource` are behaving differently @bigearsenal 


`MersenneTwister` generating different random numbers for js and swift I can confirm.

**Comment by Perronef5** [comment]
Furthermore, I think it has todo with 'mersenne-twister' using the 32bit algorithm and iOS using the 64 bit algorithm of Mersenne Twister.

**Comment by bigearsenal** [comment]
@Perronef5 yes I have just tested it. I created feature/unit-test to add test cases and doing some research. At the moment I found that the algorithms return different value, just like what you said

**Comment by Perronef5** [comment]
@bigearsenal Maybe this pod can help. They use the 32 bit version. 

https://github.com/quells/Squall

**Comment by bigearsenal** [comment]
> @bigearsenal Maybe this pod can help. They use the 32 bit version.
> 
> https://github.com/quells/Squall

Thank you. I will give it a try!

**Comment by bigearsenal** [comment]
@Perronef5 Unfortunately, the lib return different number too. Any suggestion?

**Comment by bigearsenal** [comment]
@Perronef5 Good news! I have just copied the lib and do some modifications to adapt js lib and the values now equal, you can see branch `feature/unit-test`

**Comment by Perronef5** [comment]
> @Perronef5 Good news! I have just copied the lib and do some modifications to adapt js lib and the values now equal, you can see branch `feature/unit-test`

Oh that's fantastic! Gonna test it out tonight.

Question: Could we make this library compatible with WatchOS?

**Comment by Perronef5** [comment]
@bigearsenal `Firstrot` and `secondrot` have different values for js and swift version. Some calculation is off. Looking into it

**Comment by bigearsenal** [comment]
@Perronef5 thanks. Will try to add support to other devices

**Comment by bigearsenal** [comment]
@Perronef5 added support for multiple platforms in `feature/unit-test`

**Comment by Perronef5** [comment]
@bigearsenal I have all the correct numbers being generated and the correct colors are being shown. Only problem is the rotation. When I rotate it then it looks off.

Using this for rotation `ctx.rotate(by: CGFloat(rot) * CGFloat(Double.pi / 180))`

**Comment by Perronef5** [comment]
Hi I opened this PR with the fix for generating the correct image. https://github.com/bigearsenal/JazziconSwift/pull/3 

If we can get this fix in by today that would be great!

**Comment by bigearsenal** [comment]
@Perronef5 JazziconSwift (1.1.0) successfully published with color correction, custom drawing and multi-platform support!
Thank you for your contribution!

**Comment by Perronef5** [comment]
@bigearsenal No problem! Glad I could help. I am trying to download `1.1.0` and I am getting it is unavailable. Are you sure it published?

**Comment by bigearsenal** [comment]
> @bigearsenal No problem! Glad I could help. I am trying to download `1.1.0` and I am getting it is unavailable. Are you sure it published?

There are some delays if you use cocoapods. Please wait a little bit

**Comment by Perronef5** [comment]
@bigearsenal Any chance you can bring back `generateImage` as now it is more difficult to use in SwiftUI
